version: '3.8'

services:
  app:
    image: ghcr.io/axaxin/sublinkwrap:latest
    container_name: sublinkwrap
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SESSION_SECRET=your-secret-key
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"

volumes:
  app_data:
