version: '3.8'

services:
  app:
    image: ghcr.io/axaxin/sublinkwrap:latest
    container_name: sublinkwrap
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
