version: '3.8'

services:
  app:
    image: ghcr.io/axaxin/sublinkwrap:latest
    container_name: sublinkwrap
    restart: always
    environment:
      - PORT=3000
      - GIT_BRANCH=main
    volumes:
      - app_data:/app
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  app_data:

networks:
  app_network:
    driver: bridge
